// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBItyAuB67UnxsNefvfB_iuKCdxuQkpDp8',
    appId: '1:355129915051:web:d56dece32a87e6fc1969ee',
    messagingSenderId: '355129915051',
    projectId: 'cseuniversityapp',
    authDomain: 'cseuniversityapp.firebaseapp.com',
    databaseURL: 'https://cseuniversityapp-default-rtdb.firebaseio.com',
    storageBucket: 'cseuniversityapp.appspot.com',
    measurementId: 'G-7SQJE3XLRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4GBSeiVkZw_nhrzEFVZhoUD0syX26fgE',
    appId: '1:355129915051:android:2c7922e884b344b91969ee',
    messagingSenderId: '355129915051',
    projectId: 'cseuniversityapp',
    databaseURL: 'https://cseuniversityapp-default-rtdb.firebaseio.com',
    storageBucket: 'cseuniversityapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXvQDfDj03MDah5cYY2tGsBxmyHWQm_8c',
    appId: '1:355129915051:ios:e06ce59eb91cd7931969ee',
    messagingSenderId: '355129915051',
    projectId: 'cseuniversityapp',
    databaseURL: 'https://cseuniversityapp-default-rtdb.firebaseio.com',
    storageBucket: 'cseuniversityapp.appspot.com',
    iosBundleId: 'com.example.cseUniversityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXvQDfDj03MDah5cYY2tGsBxmyHWQm_8c',
    appId: '1:355129915051:ios:e06ce59eb91cd7931969ee',
    messagingSenderId: '355129915051',
    projectId: 'cseuniversityapp',
    databaseURL: 'https://cseuniversityapp-default-rtdb.firebaseio.com',
    storageBucket: 'cseuniversityapp.appspot.com',
    iosBundleId: 'com.example.cseUniversityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBItyAuB67UnxsNefvfB_iuKCdxuQkpDp8',
    appId: '1:355129915051:web:6e779ce8036f18341969ee',
    messagingSenderId: '355129915051',
    projectId: 'cseuniversityapp',
    authDomain: 'cseuniversityapp.firebaseapp.com',
    databaseURL: 'https://cseuniversityapp-default-rtdb.firebaseio.com',
    storageBucket: 'cseuniversityapp.appspot.com',
    measurementId: 'G-EX58TCR907',
  );

}